package ch.bbw.m323;

public enum Major {
    COMPUTER_SCIENCE,
    ELECTRICAL_ENGINEERING,
    MECHANICAL_ENGINEERING,
    CIVIL_ENGINEERING,
    BUSINESS_ADMINISTRATION,
    PHYSICS,
    MATHEMATICS
}
